### ISSUE TITLE
Wrong INFO message for get-receipt

### ISSUE THREAD

**Issue by jennijuju** [bloxbean/aion4j-maven-plugin#31]
When running `aion4j:get-receipt`, [INFO] message "Waited too much for the receipt. Something is wrong." is shown even when the tx is mined and the receipt is returned properly.

![image](https://user-images.githubusercontent.com/42981373/59639664-ea2cc500-9129-11e9-9076-a7e4c4b5b137.png)

**Comment by satran004** [comment]
Really. I never noticed that. I will fix that in next release.

**Comment by satran004** [comment]
This happens only when the receipt is returned at 15th attempt (max counter).  Fixed. Fix will be available in the next release.
