### ISSUE TITLE
Add Travis test

### ISSUE THREAD

**Issue by fulldecent** [bloxbean/aion4j-maven-plugin#34]
Please add a Travis test and enable Travis CI builds to confirm builds are working.

An alternative technology is GitHub Actions, which can also provide CI builds.

---

FYI, here is a project that has Travis set up:

https://github.com/fulldecent/aion-aip010

https://travis-ci.com/fulldecent/aion-aip010

**Comment by satran004** [comment]
Added travis file 
https://github.com/bloxbean/aion4j-maven-plugin/commit/4eb6048851ee42ff968cb82b9dcc00fb52aa4021

**Comment by fulldecent** [comment]
Looks great, thank you
