### ISSUE TITLE
Combine`mvn aion4j:create-account` to `mvn aion4j:account`

### ISSUE THREAD

**Issue by jennijuju** [bloxbean/aion4j-maven-plugin#39]
Would it be better if we use `account` for all account management?

For example
1. `mvn aion4j:account -Dcreate -Dbalance` will create an account for embedded avm with a desired balance
2. `mvn aion4j:account -Dcreate` will create an account  that is useable for both local and remote network.
3. `mvn aion4j:account -Dtopup` will allocate "balance" to the accout in the embedded avm.
4. Exisiting account clis needs to be used with -Premote flag.

**Comment by satran004** [comment]
https://github.com/bloxbean/aion4j-maven-plugin/commit/6d244e6b184453298c87a631644adfe48717fd08

**Comment by satran004** [comment]
Implemented in 0.8.0-beta3
